spawn:
  # This task will run "task_command --queue sendmails" command
  # for 10 minutes and restart it. All the command output will be redirected to console.
  task 1:
    # The command to run.
    command: 'task_command'
    # List of string arguments.
    args: ['--queue', 'sendmails']
    # Environment key-value pairs.
    env:
      USERNAME: test
      DATABASE: test
    # Current working directory of the process (optional).
    cwd: /var/www/html
    # The maximum amount of time the process is allowed to run (optional).
    # Use a number or 's' suffix for secods, 'm' for minutes, 'h' for hours.
    # Valid values: 60, 60s, 30m, 4h
    timeout: 10m
    # Do not start the process command immediately and wait for specified amount of time (by default, no delay).
    start_delay: 5s
    # Restart command when timeout is over or command exited (default false).
    # Otherwise, the command started only once.
    restart: true
    # The maximum attempts to restart the failed process (by default, 3).
    max_failed_restarts: 3
    # Redirect command stdout and stderr outputs to console or a file.
    # By default, no output is collected.
    output: console
    # Sets the user identity of the process
    uid: 1000
    # Sets the group identity of the process
    gid: 1000

  # The next command will run only once.
  task 2:
    command: 'simple_command'
