name: Build app binaries
on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  workflow_dispatch:
    inputs:
      build-target-os:
        required: false
        description: 'Select target OS to build binary'
        type: choice
        options:
          - All
          - Linux
          - Windows
        default: all

jobs:
  build-linux:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build-target-os == 'Linux' || github.event.inputs.build-target-os == 'All' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: multirun-linux-x64
          path: dist/multirun-linux-x64
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/multirun-linux-x64

  build-windows:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build-target-os == 'Windows' || github.event.inputs.build-target-os == 'All' }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: multirun-win32-x64.exe
          path: dist/multirun-win32-x64.exe
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/multirun-win32-x64.exe
