name: Build app binaries
on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  workflow_dispatch:
    inputs:
      build-target-binary:
        required: false
        description: 'Select build target OS'
        type: choice
        options:
          - build-linux
          - build-windows
        default: ''

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: multirun-linux-x64
          path: dist/multirun-linux-x64
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: multirun-win32-x64.exe
          path: dist/multirun-win32-x64.exe

